#!/usr/bin/env bash
# setup_deps.sh — Fetch external dependencies for gbs-control-esp
#
# This script downloads external libraries that are NOT bundled in this
# repository for licensing reasons, and extracts the files we need.
#
# Usage:
#   ./setup_deps.sh
#
# What it does:
#   1. Clones ThingPulse/esp8266-oled-ssd1306 (MIT License)
#      → Extracts ArialMT_Plain font data into components/gbs_control/include/
#   2. (Future: add other external dependencies here)
#
# Re-running is safe — existing files will be overwritten.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPS_DIR="${SCRIPT_DIR}/.deps"
GBS_INCLUDE="${SCRIPT_DIR}/components/gbs_control/include"
GENERATED_HEADER="${GBS_INCLUDE}/OLEDDisplayFonts_ext.h"

# ThingPulse OLED library
THINGPULSE_REPO="https://github.com/ThingPulse/esp8266-oled-ssd1306.git"
THINGPULSE_TAG="4.6.1"  # Use a pinned release for reproducibility
THINGPULSE_DIR="${DEPS_DIR}/esp8266-oled-ssd1306"

echo "=== gbs-control-esp: Fetching external dependencies ==="

mkdir -p "${DEPS_DIR}"

# ─── 1. ThingPulse esp8266-oled-ssd1306 (MIT License) ───────────────
echo ""
echo "[1/1] ThingPulse esp8266-oled-ssd1306 (MIT License)"
echo "      Repo: ${THINGPULSE_REPO}"
echo "      Tag:  ${THINGPULSE_TAG}"

if [ -d "${THINGPULSE_DIR}/.git" ]; then
    echo "      → Already cloned, updating..."
    cd "${THINGPULSE_DIR}"
    git fetch --tags --quiet
    git checkout "${THINGPULSE_TAG}" --quiet 2>/dev/null || git checkout "tags/${THINGPULSE_TAG}" --quiet
    cd "${SCRIPT_DIR}"
else
    echo "      → Cloning..."
    git clone --depth 1 --branch "${THINGPULSE_TAG}" "${THINGPULSE_REPO}" "${THINGPULSE_DIR}" 2>&1 | sed 's/^/      /'
fi

# Verify the source file exists
FONTS_SRC="${THINGPULSE_DIR}/src/OLEDDisplayFonts.h"
if [ ! -f "${FONTS_SRC}" ]; then
    echo "ERROR: ${FONTS_SRC} not found!" >&2
    exit 1
fi

# Extract only the ArialMT_Plain fonts we need
echo "      → Extracting ArialMT_Plain fonts..."

cat > "${GENERATED_HEADER}" << 'HEADER_TOP'
/**
 * OLEDDisplayFonts_ext.h — Font data extracted from ThingPulse esp8266-oled-ssd1306
 *
 * AUTO-GENERATED by setup_deps.sh — do not edit manually.
 *
 * Source: https://github.com/ThingPulse/esp8266-oled-ssd1306
 * License: MIT License
 *
 * Copyright (c) 2016 by Daniel Eichhorn
 * Copyright (c) 2016 by Fabrice Weinberg
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef OLED_DISPLAY_FONTS_EXT_H_
#define OLED_DISPLAY_FONTS_EXT_H_

#include <stdint.h>

#ifndef PROGMEM
#define PROGMEM
#endif

HEADER_TOP

# Extract each ArialMT_Plain font block from OLEDDisplayFonts.h
# Format: find the const array definition and extract until the closing "};""
for FONT in ArialMT_Plain_10 ArialMT_Plain_16 ArialMT_Plain_24; do
    echo "        - ${FONT}"
    # Use awk to extract the font array block
    awk "
        /^const (uint8_t|char) ${FONT}\[/ { found=1 }
        found { print }
        found && /^};/ { found=0; print \"\" }
    " "${FONTS_SRC}" >> "${GENERATED_HEADER}"
done

echo "#endif // OLED_DISPLAY_FONTS_EXT_H_" >> "${GENERATED_HEADER}"

# Verify extraction
FONT_COUNT=$(grep -c "^const.*\[\]" "${GENERATED_HEADER}" || true)
if [ "${FONT_COUNT}" -lt 3 ]; then
    echo "WARNING: Expected 3 fonts but found ${FONT_COUNT}. Check ${GENERATED_HEADER}" >&2
    echo "         The ThingPulse font format may have changed." >&2
fi

echo ""
echo "=== Done ==="
echo "Generated: ${GENERATED_HEADER}"
echo "Fonts extracted: ${FONT_COUNT}"
echo ""
echo "The .deps/ directory can be safely deleted after extraction."
echo "The generated header is listed in .gitignore and must be regenerated on fresh clones."
